/*
*
*	-= P-STREAMER =-
*	Protioso Streamer
*	Autor: Protioso ([VGS]Protioso_OC)
*   Obs.: os valores abaixo podem ser editados conforme sua necessidade!
*
*/

#define MAX_PCS 350 /* Limite de checkpoints (altere como preferir). */
#define PCS_TEMPO_CHECAGEM 500 /* Tempo em milisegundos. */
#define PCS_RAIO_STREAM_PADRAO 30.0 /* Não usado no include, apenas para você
ter uma base e/ou usar em seus scripts */

