; Please excuse the translation in this file
; I did it using babelfish

[eg1_entries]

EG1_KILL_HELP = Dit bevel doodt u

EG1_DROP_HELP_0 = Dit bevel laat vallen u van zeer hoog
EG1_DROP_HELP_1 = Het zal u waarschijnlijk doden

EG1_DROP_MSG_0 = Het plaatsen van uw hoogte aan %.2f
EG1_DROP_MSG_1 = Heb pret!

EG1_DROP_SPLAT = %s staat te gaan op het punt SPLAT!

[eg1_spares]

EG1_NOT_LOAD = This won't be loaded
